### ISSUE TITLE
Enable Issues on GitHub

### ISSUE THREAD

**Issue by allella** [hackgvl/open-map-data-multi-layers-demo#1]
@grinstead this project is a fork and we only had one [open issue on the original project](https://github.com/SpaceCowboy326/open_data_gvl/issues).

I've enabled the issues here.

If you find things that need to be updated or contributions, then feel free to share them here.

This repo is hosted on an Apache server and I have it sort of bubble-gum and duck taped in because I have no experience hosting javascript apps.  So, I could also try to redeploy updates to the existing site and post the errors or roadblocks I was getting with hosting this demo map.

**Comment by oliviasculley** [comment]
This is currently being hosted and deployed automatically with github actions, so this issue probably isn't relevant anymore!
