### ISSUE TITLE
Display map layer contributors

### ISSUE THREAD

**Issue by oliviasculley** [hackgvl/open-map-data-multi-layers-demo#11]
Similar to https://github.com/hackgvl/OpenData/issues/54, it would be nice to display credits for the maintainers of the map layers when they are loaded.

This could also be expanded into a mechanism to contribute as described in #10

**Comment by ThorntonMatthewD** [comment]
Is the idea for information be displayed for each active layer?

**Comment by oliviasculley** [comment]
I think so, but the specifics of how can be up to you :smile:

**Comment by ThorntonMatthewD** [comment]
![Screenshot_2023-10-07_19-42-35](https://github.com/hackgvl/open-map-data-multi-layers-demo/assets/44626690/f1200550-475b-48e9-b410-d3ea429d0c05)

I think the built-in "attribution bar" could get really busy if more than just one set of markers is active at one time, and we are displayed maintainer/contribution links for all of them. I like the idea of using this element to make a call out to hg-labs and the [How to Contribute](https://data.openupstate.org/contribute) page, though.

**Comment by ThorntonMatthewD** [comment]
I'm still getting my bearings with Vue and Tailwind, but this is a prototype of what I've been envisioning:

https://github.com/hackgvl/open-map-data-multi-layers-demo/assets/44626690/fad7410f-d316-4b14-86d9-3efb67371946

I'd appreciate any feedback anyone may have on this. I'm still working on the finer points around the styling, but I think the overall picture is there.

**Edit:**

Here it is on the mobile view.

https://github.com/hackgvl/open-map-data-multi-layers-demo/assets/44626690/a82a0cb6-74de-4878-bc21-8543f6229fc8

**Comment by oliviasculley** [comment]
This looks fantastic! I think the only catch with this solution is making sure that it is accessible with screen readers and such, but for now we can just get this implemented, and then work on fixing any accessibility warnings that appear when viewing it in chrome or firefox, and then maybe adding better accessibility checks/tests to the CI pipeline like in #18. But all of this is outside of the scope of this issue. I'm really excited for this PR :smile:

**Comment by ThorntonMatthewD** [comment]
Thank you so much! I do have a few aria labels to add to some elements to get the accessibility score back up. I'll make sure that's all polished before I submit this for review.
