### ISSUE TITLE
Add more e2e tests

### ISSUE THREAD

**Issue by oliviasculley** [hackgvl/open-map-data-multi-layers-demo#2]
Currently there are no e2e tests for several things:

- [ ] Checking and unchecking a map layer (and having the URL update)
- [ ] Panning/zooming around the map (and having the URL update)
- [ ] Making sure all the tabs render properly

Bonus points if the api's response can be mocked so the tests aren't dependent on the status of the OpenData api!

**Comment by eitan-lich** [comment]
Hi, could i perhaps be assigned to this task?
Thanks

**Comment by eitan-lich** [comment]
Hi, could i perhaps be assigned to this task?
Thanks

**Comment by oliviasculley** [comment]
Of course, it'd be a great help! Thank you!

**Comment by eitan-lich** [comment]
Hi again, i have opened a pull request.
I'm not that experienced with Cypress but i hope its okay.

**Comment by oliviasculley** [comment]
Closed by #3
