### ISSUE TITLE
Create a 404 or Default Page

### ISSUE THREAD

**Issue by ThorntonMatthewD** [hackgvl/open-map-data-multi-layers-demo#29]
Create a default "catch-all" route for anything that doesn't match up with a view.

Current view of `/meow`:
![Screenshot_2023-10-14_00-24-00](https://github.com/hackgvl/open-map-data-multi-layers-demo/assets/44626690/bd25108d-28d3-4d3f-a492-c3e9d2b4b9c8)

Maybe the default page could just be the map?

**Comment by ChaudaryHammad** [comment]
assign it to me i can do this

**Comment by Alex-Grimes** [comment]
Would something like this work or should it be more generic? 
![image](https://github.com/hackgvl/open-map-data-multi-layers-demo/assets/66704965/243b0737-7d10-4db3-8670-93bbfaeb5e05)

**Comment by ThorntonMatthewD** [comment]
I think it looks really cool! Do you happen to have a screenshot of how it appears on mobile?

**Comment by Alex-Grimes** [comment]
probably need to do some tweaking for mobile views.
![image](https://github.com/hackgvl/open-map-data-multi-layers-demo/assets/66704965/6c7a152b-4f47-473d-9009-9f9dd0181789)

**Comment by ThorntonMatthewD** [comment]
How is the graphic configured? I think it it could more-or-less scale with the size of the viewport it'd look good there too!

**Comment by Alex-Grimes** [comment]
yeah ill need to play around with it its using some absolutes with offsets now so will need to figure out the scaling
