### ISSUE TITLE
Map tiles fail to load at max zoom

### ISSUE THREAD

**Issue by ThorntonMatthewD** [hackgvl/open-map-data-multi-layers-demo#32]
The maximum zoom on the map is [currently set to 20](https://github.com/hackgvl/open-map-data-multi-layers-demo/blob/711a57ac5df9b07bcd640a42dfa816de5d0a8347/src/components/MainMap.vue#L223), however at this zoom level the map tiles appear as solid grey images.

![Screenshot_2023-10-16_20-00-39](https://github.com/hackgvl/open-map-data-multi-layers-demo/assets/44626690/83f57198-8c42-4536-a38d-6834be52acbf)

You can see it in action here: https://hackgvl.github.io/open-map-data-multi-layers-demo/?lat=34.851224882536776&lng=-82.39967912435533&zoom=20&maps=free-wi-fi-hotspots

I'm wondering if the max zoom needs to be 18 instead since it seems to be inclusive.

**Comment by oliviasculley** [comment]
There's actually also a bigger issue with tiles in that we should probably find a better alternative than freeloading off of open street map's donation-based tile servers, which could change their policy at any time: https://operations.osmfoundation.org/policies/tiles/

**Comment by ThorntonMatthewD** [comment]
My vote is for [Spinal Map](https://www.thunderforest.com/maps/spinal-map/) for the remainder of October. 🎃🤘

That is a really good point... I've seen some projects store their base tiles in a GitHub repo, but I'm not sure what limits we'd run into there in the long run.

**Comment by Alex-Grimes** [comment]
Spinal Map looks amazing 😆. I could do some research on alternative options for tile servers. Is a PR to lower the zoom limit to 18 still wanted?

**Comment by ThorntonMatthewD** [comment]
I think for now that would be good. If/when a different source of tiles is put into place then perhaps it can be increased again (if supported).

**Comment by ThorntonMatthewD** [comment]
#36 fixes #32

Thank you, @Alex-Grimes !!!

**Comment by allella** [comment]
Related conversation at https://github.com/hackgvl/meta/issues/18#issuecomment-1894104063
