### ISSUE TITLE
Nav bar no longer appears on mobile

### ISSUE THREAD

**Issue by ThorntonMatthewD** [hackgvl/open-map-data-multi-layers-demo#33]
![Screenshot_20231016-233538](https://github.com/hackgvl/open-map-data-multi-layers-demo/assets/44626690/a8d4d22c-036b-4ec7-bfce-1ca7cb36c7e6)

For some reason the navbar isn't appearing on mobile devices, however it works in mobile view on desktops.

I've reproduced this issue on Chrome, Brave and Firefox on an Android device. 🥺

**Comment by oliviasculley** [comment]
Hmm strange, should we put the fixed class back?

**Comment by ThorntonMatthewD** [comment]
@oliviasculley Yes, that is what caused it. I'm sorry about that! I'll be using the `--host` param to allow myself to validate changes on an actual mobile device from now on, because I had now idea how funky viewports are on those things and I bet that's not their only quirk lol
