### ISSUE TITLE
Docs: Update About Page /src/views/AboutView.vue, README, and Whatever Else, From CFG to HG Labs

### ISSUE THREAD

**Issue by allella** [hackgvl/open-map-data-multi-layers-demo#5]
@oliviasculley I'm reminded this demo was under the Code For Greenville domain / GitHub Pages, which is now redirected to Code For The Carolinas.

The new GH Pages URL is working
https://hackgvl.github.io/open-map-data-multi-layers-demo/

I've updated the demo link on [the main Maps page](https://data.openupstate.org/map-layers), but I suppose we could consider hosting this under the data.openupstate.org domain, or even under the HackGreenville domain.  I think I'd prefer the data.openupstate.org unless / until we have a plan for what fits under the HG site and what is best on another domain.

Also, the About page references CFG and the CFG GitHub repo, so we should at least update those to the HG equivalents
https://hackgvl.github.io/open-map-data-multi-layers-demo/about

**Comment by oliviasculley** [comment]
These are all good points, I'm good with any of the domains, but the nameservers need to be set up to work with Github Pages IIRC. What do you think about `https://map.openupstate.org`? Would be short and sweet and make sense :smile:

**Comment by allella** [comment]
I think we should talk about domains and such, perhaps during or after the July 10th HG meeting.

So, for now we can probably just work with the github.io link

**Comment by oliviasculley** [comment]
This has been mostly addressed with #6 and #7, but may need another small change once we choose a final domain name, so not closing this issue just yet.

**Comment by oliviasculley** [comment]
Actually, closing this issue in favor of choosing a final domain name with #9
