### ISSUE TITLE
Bug: Workaround for Breaking Issue When Map Point Features.Properties Are Numeric Values

### ISSUE THREAD

**Issue by allella** [hackgvl/open-map-data-multi-layers-demo#8]
@oliviasculley I noticed the Recycling layer wasn't rendering on the [Demo Map](https://hackgvl.github.io/open-map-data-multi-layers-demo/), or in [the map preview](https://data.openupstate.org/map/preview/recycling-locations).

The GeoJSON is fine and the issue, at least with the [map preview](https://data.openupstate.org/map/preview/recycling-locations), is the recycling data has zip codes as one of the key:value pair in map point data _features.properties_ values.

I think we both have custom JS to find and replace underscores and to force URLs in the features.properties into HTML links for the pop-ups when a point is clicked on the map.

The Javascript is seeing the zip code as a numeric type, which was breaking the String.replaceAll() I was using on the map preview.

So, it may be breaking the underscore replace() or URL replace you're using in https://github.com/hackgvl/open-map-data-multi-layers-demo/blob/stable/src/components/MainMap.vue around the _onEachFeature_ section starting around line 123.

I'm not sure if what I did is the most elegant, but forcing the features.properties key and value to a string with toString() fixed it.

 
`var popuphtml = popuphtml + "<li><strong>" + key.toString().replaceAll('_', ' ').toProperCase() + "</strong>: " + value.toString().replaceAll(urlRegEx, '<a href="$1">$1</a>') + "</li>"
`

![image](https://github.com/hackgvl/open-map-data-multi-layers-demo/assets/1777776/ee2db924-1452-438f-a50c-d0443482a2f9)

![image](https://github.com/hackgvl/open-map-data-multi-layers-demo/assets/1777776/a50215cb-4104-4e94-bd71-f10a3092f699)

**Comment by oliviasculley** [comment]
Great catch! [Recycling locations](https://hackgvl.github.io/open-map-data-multi-layers-demo/?lat=34.868327491668&lng=-82.32347488403322&zoom=12&maps=recycling-locations) should be working again!
